services:
- type: web
  name: meili
  env: docker
  repo: https://github.com/joshio1/meilisearch-docker-render.git
  plan: starter
  disk:
    name: meili-data
    mountPath: /meili-data
    sizeGB: 5  
  envVars:
  - key: MEILI_HTTP_ADDR
    value: 0.0.0.0:80
  - key: MEILI_MASTER_KEY
    generateValue: false
  - key: MEILI_DB_PATH
    value: /meili-data
  - key: MEILI_ENV
    value: development
